export default {
  VIEW_ITEM: 'VIEW_ITEM',
  CLOSE_ITEM: 'CLOSE_ITEM',
  LOAD_ITEM: 'LOAD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  SAVE_ITEM: 'SAVE_ITEM',
  RATE_ITEM: 'RATE_ITEM',
  LOAD_ITEMS: 'LOAD_ITEMS',
  LOAD_HITLIST: 'LOAD_HITLIST',
  SAVE_ITEM_HITLIST: 'SAVE_ITEM_HITLIST',
  DELETE_ITEM_HITLIST: 'DELETE_ITEM_HITLIST'
}